server {
    listen 80;
    server_name localhost;
    location /api {
        rewrite ^/api/(.*)$ /$1 break;
        proxy_pass http://notes_backend:9000;
        proxy_http_version 1.1;
    }

    location / {
        proxy_pass http://notes_frontend:3000;
        proxy_http_version 1.1;
    }
}
