// Use DBML to define your database structure
// Docs: https://dbml.dbdiagram.io/docs

Table situations {
  id number [primary key]
  description varchar [not null]
  slug varchar [not null]
}

Table roles {
  id number [primary key]
  description varchar [unique, not null]
  slug varchar [unique, not null]
}

Table users_roles {
  role_id number [ref: > roles.id, not null, primary key]
  user_uuid uuid [ref: > users.uuid, not null, primary key]
  access_date datetime [not null]
}

Table permissions {
  id number [primary key]
  description varchar [unique, not null]
  slug varchar [unique, not null]
}

Table access_text {
  user_uuid uuid [not null, ref: > users.uuid, primary key]
  text_id number [not null, ref: > texts.id, primary key]
  permissions_id number [not null, ref: > permissions.id] 
}

Table users {
  uuid uuid [primary key]
  email varchar [unique, not null]
  username varchar [unique, not null]
  password varchar [not null]
  created timestamp [not null]
  modified timestamp
  situation_id number [not null, ref: > situations.id]
}

Table texts_situations {
  id number [primary key]
  description varchar [unique, not null]
  slug varchar [unique, not null]
}

Table texts {
  id number [primary key]
  title varchar [not null]
  description text [not null]
  text_own_uuid hash [ref: - users.uuid, not null]
  situation_text_id number [ref: > texts_situations.id, not null]
}
